### ISSUE TITLE
More compact output

### ISSUE THREAD

**Issue by Mutantpenguin** [MindLaborDev/bonza-commit#13]
I think it would be nicer to have a more compact output like this:
![image](https://user-images.githubusercontent.com/9027507/105979318-d4b4a680-6093-11eb-97e5-2bd2e20f5395.png)

Just state the name of each file once, and then have multiple lines with each hit for this file.

**Comment by web-dev-sam** [comment]
That's a great idea, I'll look into it :D

**Comment by web-dev-sam** [comment]
In the current non-compact format, it is possible to jump to the exact line of the issue within VS Code and probably other editors. For this reason, I implemented the compact output as an optional command-line argument `/.bonza/check --compact`. 

<img width="545" alt="Skjermbilde 2021-01-27 191332" src="https://user-images.githubusercontent.com/42311986/106034932-cedeb580-60d3-11eb-9793-c1a32d1d95fa.png">

Note: In the compact output mode, it is still possible to jump to the file within VS Code but not to the exact line.
